### ISSUE TITLE
Build fails with 5.2.0 - Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by jedashford** [pusherman/react-native-network-info#103] opened 2019-09-23 20:00 UTC
Issue below is with 5.2.0, but not with 5.1.0 when building on iOS. Looks like it might be related to the addition of getGatewayIPAddress

Undefined symbols for architecture x86_64:
  "_getdefaultgateway", referenced from:
      -[RNNetworkInfo getGatewayIPAddress:rejecter:] in libreact-native-network-info.a(RNNetworkInfo.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by antonkulyk** [comment] 2019-09-24 16:58
Experiencing the same problem. Looks like the problem has appeared in #98 
@parrotmac maybe you have an idea on a fix?

**Comment by gabrielrra** [comment] 2019-09-27 18:41
Having the same issue here also

**Comment by umutcetinkaya** [comment] 2019-09-29 18:10
i have same problem. Does anyone have a solution?

**Comment by antonkulyk** [comment] 2019-09-30 09:23
This pull request looks like a fix #106

**Comment by SkyPeer** [comment] 2019-09-30 18:29
> This pull request looks like a fix #106

Awesome! 
thank you very much!

**Comment by pusherman** [comment] 2019-09-30 18:46
I just confirmed it does, will be releasing an update by EOD.

**Comment by pusherman** [comment] 2019-09-30 21:52
Should be fixed in 5.2.1.

**Closed by pusherman** 2019-09-30 21:52 UTC
