### ISSUE TITLE
this is an error happening on android when making a release

### ISSUE THREAD

**Issue by sibelius** [pusherman/react-native-network-info#16] opened 2017-03-06 20:56 UTC
Error: The WIFI_SERVICE must be looked up on the Application context or memory will leak on devices < Android N. Try changing reactContext to reactContext.getApplicationContext()  [WifiManagerLeak]
    wifi = (WifiManager)reactContext.getSystemService(Context.WIFI_SERVICE);
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "WifiManagerLeak":
   On versions prior to Android N (24), initializing the WifiManager via
   Context#getSystemService can cause a memory leak if the context is not the
   application context. Change context.getSystemService(...) to
   context.getApplicationContext().getSystemService(...).

**Comment by pusherman** [comment] 2017-03-11 03:51
@indraastra is there anyway you can test this suggested change out?  I don't have an android device around to test.

**Comment by sibelius** [comment] 2017-03-11 13:04
try to run in the emulator

**Comment by pusherman** [comment] 2017-03-24 20:05
@sibelius I was able to reproduce this in the emulator.  I made the suggested change and the error went away.  The problem is-- the IP and SSID are not shown in the emulator ever so I don't have a device that I can test things on to make sure everything is still working.

If I make the change and push it up to a different branch would you mind testing it out on an actual device for me?

**Comment by sibelius** [comment] 2017-03-24 20:07
I could test for sure

**Comment by pusherman** [comment] 2017-03-24 20:19
just pushed a fix to a new branch
https://github.com/pusherman/react-native-network-info/tree/bug/android_memory_leak

Thanks for testing!

**Comment by sibelius** [comment] 2017-03-24 20:25
could you open the pull request?

**Comment by pusherman** [comment] 2017-03-24 20:35
There you go

**Comment by pusherman** [comment] 2017-03-30 17:32
@sibelius were you ever able to test this out?

**Closed** 2017-04-07 13:50 UTC

**Comment by sibelius** [comment] 2017-04-07 14:18
sorry for not testing, I had a lot of work to finish here in my startup

**Comment by pusherman** [comment] 2017-04-07 14:23
No worries, I found an android device to test on myself.  Let me know if you find any problems with the new release!
